name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Vérification du Token Railway
        run: |
          echo "🔍 Vérification du token Railway..."
          if [[ -z "${{ secrets.RAILWAY_PROJECT_TOKEN }}" ]]; then
            echo "❌ ERREUR : La variable d'environnement RAILWAY_PROJECT_TOKEN est vide !"
            exit 1
          else
            echo "✅ RAILWAY_PROJECT_TOKEN est bien défini."
          fi

      - name: Configurer le token Railway dans l'environnement CI/CD
        run: |
          echo "📌 Configuration de Railway..."
          railway env set RAILWAY_TOKEN="${{ secrets.RAILWAY_PROJECT_TOKEN }}"

      - name: Déployer sur Railway
        run: railway up --ci