name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Vérifier que le token Railway est bien défini
        run: |
          if [[ -z "${{ secrets.RAILWAY_PROJECT_TOKEN }}" ]]; then
            echo "❌ ERREUR : RAILWAY_PROJECT_TOKEN n'est pas défini dans GitHub Secrets !"
            exit 1
          else
            echo "✅ RAILWAY_PROJECT_TOKEN est bien défini."
          fi

      - name: Déployer sur Railway avec authentication forcée
        run: |
          export RAILWAY_TOKEN=${{ secrets.RAILWAY_PROJECT_TOKEN }}
          railway up --ci